/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Opcion;
import modelo.PersistenciaPregunta;
import modelo.Pregunta;

/**
 *
 * @author T-101
 */
public class TestAplicacion extends javax.swing.JFrame {
int numero=0;

    /**
     * Creates new form TestAplicacion
     */
    public TestAplicacion() {
        initComponents();
        setLocationRelativeTo(this);
        setSize(500,400);
        mostrarPregunta(numero++);
        
    }
    public void mostrarPregunta(int numero){
        try {
            //Primero sacamos la pregunta de numero dado
            ArrayList<Pregunta> preguntas=PersistenciaPregunta.leer();
            Pregunta p= preguntas.get(numero);
            //Ajustamos los valores
            //Primero va el titulo
            EtiquetaPregunta.setText(p.getTitulo());
            //Ahora van las opciones
            ArrayList<Opcion> opciones=p.getOpcion();
            //Aplicamos el algotirmo
            opciones= PersistenciaPregunta.opcionesAleatorias(opciones);
            Rb1.setText(opciones.get(0).getTitulo());
            Rb2.setText(opciones.get(1).getTitulo());
            Rb3.setText(opciones.get(2).getTitulo());
            Rb4.setText(opciones.get(3).getTitulo());
        } catch (Exception ex) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Pregunta = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        EtiquetaTiempo = new javax.swing.JLabel();
        EtiquetaPregunta = new javax.swing.JLabel();
        Rb1 = new javax.swing.JRadioButton();
        Rb2 = new javax.swing.JRadioButton();
        Rb3 = new javax.swing.JRadioButton();
        Rb4 = new javax.swing.JRadioButton();
        Continuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        Pregunta.setLayout(new javax.swing.BoxLayout(Pregunta, javax.swing.BoxLayout.Y_AXIS));

        Titulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Titulo.setText("Contestar Test");
        Pregunta.add(Titulo);

        EtiquetaTiempo.setText("Tiempo");
        Pregunta.add(EtiquetaTiempo);

        EtiquetaPregunta.setText("Aqui va la pregunta");
        Pregunta.add(EtiquetaPregunta);

        buttonGroup1.add(Rb1);
        Rb1.setText("jRadioButton1");
        Pregunta.add(Rb1);

        buttonGroup1.add(Rb2);
        Rb2.setText("jRadioButton2");
        Pregunta.add(Rb2);

        buttonGroup1.add(Rb3);
        Rb3.setText("jRadioButton3");
        Pregunta.add(Rb3);

        buttonGroup1.add(Rb4);
        Rb4.setText("jRadioButton4");
        Pregunta.add(Rb4);

        Continuar.setText("Siguiente");
        Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarActionPerformed(evt);
            }
        });
        Pregunta.add(Continuar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarActionPerformed
    
        // TODO add your handling code here:
        mostrarPregunta(numero++);
    }//GEN-LAST:event_ContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continuar;
    private javax.swing.JLabel EtiquetaPregunta;
    private javax.swing.JLabel EtiquetaTiempo;
    private javax.swing.JPanel Pregunta;
    private javax.swing.JRadioButton Rb1;
    private javax.swing.JRadioButton Rb2;
    private javax.swing.JRadioButton Rb3;
    private javax.swing.JRadioButton Rb4;
    private javax.swing.JLabel Titulo;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
